//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogFileViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\appserverms.qa.fiadmin.com\\PureFILogs\\qa-manual\\FI.Claim")]
        public string QALogsManual {
            get {
                return ((string)(this["QALogsManual"]));
            }
            set {
                this["QALogsManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\appserverms.qa.fiadmin.com\\PureFILogs\\qa-automation\\FI.Claim")]
        public string QALogsAutomation {
            get {
                return ((string)(this["QALogsAutomation"]));
            }
            set {
                this["QALogsAutomation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fileserver.prod.fiadmin.com\\purefilogs\\migrate\\FI.Claim")]
        public string ProductionClaim {
            get {
                return ((string)(this["ProductionClaim"]));
            }
            set {
                this["ProductionClaim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fileserver.uat.fiadmin.com\\purefilogs\\uat\\FI.Claim")]
        public string UATLogs {
            get {
                return ((string)(this["UATLogs"]));
            }
            set {
                this["UATLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\appserverms.release.fiadmin.com\\PureFILogs\\release-automation\\FI.Claim")]
        public string ReleaseAutomationClaim {
            get {
                return ((string)(this["ReleaseAutomationClaim"]));
            }
            set {
                this["ReleaseAutomationClaim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\appserverms.release.fiadmin.com\\PureFILogs\\release-Manual\\FI.Claim")]
        public string ReleaseManualClaim {
            get {
                return ((string)(this["ReleaseManualClaim"]));
            }
            set {
                this["ReleaseManualClaim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\fileserver.uat.fiadmin.com\\purefilogs\\uat\\FI.Claim")]
        public string UATClaim {
            get {
                return ((string)(this["UATClaim"]));
            }
            set {
                this["UATClaim"] = value;
            }
        }
    }
}
