//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Substitutions {
            get {
                return ((string)(this["Substitutions"]));
            }
            set {
                this["Substitutions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\GIT\\fi.packages.core.Master\\src\\fi.packages.core\\Entities")]
        public string EntityFolder {
            get {
                return ((string)(this["EntityFolder"]));
            }
            set {
                this["EntityFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_[a-zA-Z0-9]+")]
        public string ClassNameExpression {
            get {
                return ((string)(this["ClassNameExpression"]));
            }
            set {
                this["ClassNameExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI.Claim")]
        public string Namespace {
            get {
                return ((string)(this["Namespace"]));
            }
            set {
                this["Namespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NamespaceSuffix {
            get {
                return ((string)(this["NamespaceSuffix"]));
            }
            set {
                this["NamespaceSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfrastructureServicesMappingFolder {
            get {
                return ((string)(this["InfrastructureServicesMappingFolder"]));
            }
            set {
                this["InfrastructureServicesMappingFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UnitTestFolder {
            get {
                return ((string)(this["UnitTestFolder"]));
            }
            set {
                this["UnitTestFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TestDataFolder {
            get {
                return ((string)(this["TestDataFolder"]));
            }
            set {
                this["TestDataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfrastructureServicesFolder {
            get {
                return ((string)(this["InfrastructureServicesFolder"]));
            }
            set {
                this["InfrastructureServicesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfrastructureServiceUnitTestFolder {
            get {
                return ((string)(this["InfrastructureServiceUnitTestFolder"]));
            }
            set {
                this["InfrastructureServiceUnitTestFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfrastructureServicesProjectFolder {
            get {
                return ((string)(this["InfrastructureServicesProjectFolder"]));
            }
            set {
                this["InfrastructureServicesProjectFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfrastructureServicesQueryFolder {
            get {
                return ((string)(this["InfrastructureServicesQueryFolder"]));
            }
            set {
                this["InfrastructureServicesQueryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TestDataNamespace {
            get {
                return ((string)(this["TestDataNamespace"]));
            }
            set {
                this["TestDataNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PostSQLSnippet {
            get {
                return ((string)(this["PostSQLSnippet"]));
            }
            set {
                this["PostSQLSnippet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfrastructureServicesInterfacesFolder {
            get {
                return ((string)(this["InfrastructureServicesInterfacesFolder"]));
            }
            set {
                this["InfrastructureServicesInterfacesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QueryUnitTestFolder {
            get {
                return ((string)(this["QueryUnitTestFolder"]));
            }
            set {
                this["QueryUnitTestFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReferencedNamespaces {
            get {
                return ((string)(this["ReferencedNamespaces"]));
            }
            set {
                this["ReferencedNamespaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GitRepositoryFolder {
            get {
                return ((string)(this["GitRepositoryFolder"]));
            }
            set {
                this["GitRepositoryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI.Domain.Entities")]
        public string InfrastructureEntityNamespace {
            get {
                return ((string)(this["InfrastructureEntityNamespace"]));
            }
            set {
                this["InfrastructureEntityNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Int16=i,n,bt;Int32=i,n,bt,Int64=i,n,bt;Byte=i,n,bt;AnsiString=s;AnsiStringFixedLe" +
            "ngth=s;String=s;StringFixedLength=s;Date=dt;DateTime=dt;DateTime2=dt;Currency=c;" +
            "Decimal=c;Boolean=bt;VarNumeric=n")]
        public string TypePrefixes {
            get {
                return ((string)(this["TypePrefixes"]));
            }
            set {
                this["TypePrefixes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI.Claim.Mappings")]
        public string MappingNamespace {
            get {
                return ((string)(this["MappingNamespace"]));
            }
            set {
                this["MappingNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI.Claim.Services")]
        public string ServicesNamespace {
            get {
                return ((string)(this["ServicesNamespace"]));
            }
            set {
                this["ServicesNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI.Claim.Tests.MockData")]
        public string MockDataNamespace {
            get {
                return ((string)(this["MockDataNamespace"]));
            }
            set {
                this["MockDataNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI.Claim.Tests.UnitTests")]
        public string UnitTestNamespace {
            get {
                return ((string)(this["UnitTestNamespace"]));
            }
            set {
                this["UnitTestNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI.Claim.Queries")]
        public string QueryNamespace {
            get {
                return ((string)(this["QueryNamespace"]));
            }
            set {
                this["QueryNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FI.Core")]
        public string InfrastructureNamespace {
            get {
                return ((string)(this["InfrastructureNamespace"]));
            }
            set {
                this["InfrastructureNamespace"] = value;
            }
        }
    }
}
